on:
  workflow_dispatch:
  schedule:
  - cron: "0 */12 * * *"

jobs:
  main:
    name: "Running main.sh"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Cache
        uses: actions/cache@v3
      - name: Collect and reformat
        run: bash main.sh
      - name: Commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add release/* serenity.db servers.json servers-lite.json
          git commit -m "`date '+Collected on %Y: day %j, %T'`"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
